plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id "co.uzzu.dotenv.gradle" version "2.0.0"
	id "com.matthewprenger.cursegradle" version "1.4.0"
	id "com.modrinth.minotaur" version "2.+"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}
	maven {
		name = "Ladysnake Libs"
		url = 'https://maven.ladysnake.org/releases'
	}
	maven {
		name = "Nucleoid"
		url = 'https://maven.nucleoid.xyz/releases'
		metadataSources {
			artifact()
		}
	}
	maven {
		name 'Configuration'
		url 'https://repo.repsy.io/mvn/toma/public/'
	}
	maven {
		name 'Configuration (alternative/backup)'
		url 'https://api.repsy.io/mvn/toma/public/'
	}
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Cardinal Components
	api include("dev.onyxstudios.cardinal-components-api:cardinal-components-base:${project.cca_version}")
	api include("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:${project.cca_version}")

	// Trinkets API
	implementation "eu.pb4:trinkets:${project.trinkets_version}"

	// ModMenu
	compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
	localRuntime("com.terraformersmc:modmenu:${project.modmenu_version}")

	// Configuration
	implementation "dev.toma.configuration:configuration-fabric:${project.configuration_version}"
}

processResources {
	inputs.properties([
	        version: project.version,
			loader_version: project.loader_version,
			minecraft_depends: project.minecraft_depends,
			configuration_version: project.configuration_version
	])

	filesMatching("fabric.mod.json") {
		expand inputs.properties
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

import com.modrinth.minotaur.dependencies.ModDependency

modrinth {
	token = env.MODRINTH_TOKEN.value
	projectId = 'YTVu0oG8'
	versionNumber = project.mod_version
	versionName = 'VanitySlots ' + project.mod_version
	uploadFile = jar
	gameVersions = List<String>.of(project.functional_versions.split(","))
	loaders = ['fabric', 'quilt']
	changelog = file("changelog.md").text
	dependencies = [
			new ModDependency('P7dR8mSH', 'required'), // Fabric API
			new ModDependency('3WjjSM5O', 'required'), // Configuration
			new ModDependency('XaT8sLP6', 'required'), // Trinkets Updated
			new ModDependency('mOgUt4GM', 'optional') // Mod Menu
	]
}

curseforge {
	apiKey = env.CURSEFORGE_TOKEN.value
	project {
		id = '570109'
		releaseType = 'release'
		changelog = file("changelog.md").text
		changelogType = 'markdown'

		for (version in functional_versions.split(",")) {
			addGameVersion(version)
		}

		addGameVersion "Java 25"
		addGameVersion "Fabric"
		addGameVersion "Quilt"

		relations {
			requiredDependency("fabric-api")
			requiredDependency("configuration")
			requiredDependency("trinkets-updated")
			optionalDependency("modmenu")
		}

		mainArtifact(jar.archiveFile) {
			displayName = 'VanitySlots ' + project.mod_version
		}

		afterEvaluate {
			uploadTask.dependsOn jar
		}
	}
	options {
		forgeGradleIntegration = false
	}
}
